name: docker-socket-proxy
services:
  dockerproxy:
    container_name: dockerproxy
    restart: always
    image: zoeyvid/docker-socket-proxy:latest # or ghcr.io/zoeyvid/docker-socket-proxy:latest
    pull_policy: always
    ports:
      - "127.0.0.1:2375:2375"
      - "127.0.0.1:2376:2376"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "TZ=Europe/Berlin"
